### PR TITLE
Minor fixes: typos, missing/broken references, style improvements

### PR DESCRIPTION
**Pull request by mrossinek**
### Summary
This PR introduces a few minor fixes such as fixing typos, replacing previously broken and adding previously missing references as well as some style improvements on non-notebook files.

### Details and comments
Some additional and not-so-general changes are listed below:
- `.gitignore` now properly handles any `.ipynb_checkpoints` directory anywhere
- two notebooks had unnecessary execute permissions which were removed
- the installation instructions were updated to follow IBMQ v2

### Open Todos (open for discussion)
- [ ] many notebooks include `The latest version of this notebook is available on https://github.com/Qiskit/qiskit-tutorials.` at the top. This link is old (but still working). I am happy to update all of those links, if this is wanted. [**open for discussion**]
- [x] fix remaining typos in `fundamentals` notebooks
- [x] fix remaining typos in `advanced/terra` notebooks
- [x] fix remaining typos in `advanced/aer` notebooks
- [x] fix remaining typos in `advanced/ignis` notebooks
- [x] fix remaining typos in `advanced/aqua` notebooks
- [x] resolve merge conflicts

### CODE REVIEW

**Comment by mrossinek** [comment]
I consider this PR ready for review and merging.

The last two remaining points for discussion are my own pending review regarding a broken link that I could not find a suitable replacement for and the final open task which I would like to discuss before resolving.

I am open for any feedback :)

**Comment by jaygambetta** [comment]
is it ok to split up into a smaller pr as 71 files takes a while to go though

**Comment by mrossinek** [comment]
> is it ok to split up into a smaller pr as 71 files takes a while to go though

Yes ofcourse! I totally didn't consider this when I started out working on this... Should I break it up per module? I.e. one for fundamentals and then one for each element in advanced?
That would make it 5 (maybe 6 if I take out the README and INSTALL into another separate one).

**Comment by jaygambetta** [comment]
thanks

**Comment by mrossinek** [comment]
Ah damn I'm not sure if I split them up correctly...
I just noticed that all previous commits are still present in all later branches..
Sorry about that. Will those parts still work?

**Comment by nonhermitian** [comment]
So I went through the remaining 3-8 PR's and merged them.  The sheer number of edits @mrossinek made is quite impressive, and we thank you for taking your time to go through all of those!

Closing this PR now as I do not think it is needed anymore.

**Comment by mrossinek** [comment]
@nonhermitian Thanks for taking the time to review the PRs. I agree that this one can be closed.
I just wanted to mention that we never discussed the final Todo I left open in this PR's description. Should we update all those links or shall we keep them the way they are since they still appear to be working?

**Comment by nonhermitian** [comment]
I think updating is a good idea.

**Comment by mrossinek** [comment]
> I think updating is a good idea.


See #812.

**Comment by mrossinek** [comment]
Also what about this link I found? I mentioned this further up top in a review on the line where it occurs. I have no idea where the resources went that were originally there.

https://qiskit.org/documentation/aqua/extending.html#extending-aqua

**Pull request closed without merging**
