### PR TITLE
Add CR Rabi experiment and remove spectroscopy experiment

### LINKED ISSUE #732: Add CR Rabi in Pulse
Add a CR Pulse into https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/calibrating_a_qubit.ipynb

### PR DESCRIPTION
**Pull request by nkanazawa1989**
### Summary
close #732 

### Details and comments
Two pulse echoed CR sequence is used to observe CR Rabi.

### CODE REVIEW

**Comment by nonhermitian** [comment]
This should probably not be notebook 1 in ignis

**Comment by dcmckayibm** [comment]
Typo: You can check if your conrtol qubit and target qubit are connected by bus.

**Comment by dcmckayibm** [comment]
I'd like to remove the "Running Rabi Experiment with Different Frequencies" section and put that into a notebook in the community folder because it's not really part of a typical calibration, but it is a cool experiment

**Comment by dcmckayibm** [comment]
I'd only take the CR to 0.2 amplitude and then fit it like the rabi oscillation to show where we do a CR pi/2 pulse which is the foundation of the CNOT gate

**Comment by nkanazawa1989** [comment]
I think removing frequency sweep should be in another pr, but currently this is an unique example to show how to change the oscillator frequency. if we remove this, we should add spectroscopy experiment instead.

ok, I'll add fitting in the amplitude range.

**Comment by dcmckayibm** [comment]
The frequency sweep and spectroscopy can still be notebooks (and they're good ideas), but in the communities tutorial repo. If someone just runs this whole notebook it will get bogged down on that section.

**Comment by nkanazawa1989** [comment]
I understand your concern. maybe just to comment lines to submit jobs out is effective to prevent such situation. I added a fit of cr rabi anyways.

**Comment by nonhermitian** [comment]
This has a conflict.

**Comment by dcmckayibm** [comment]
I think you might have to repull the current repo and apply your changes on top of that version. When you do that can you also pull out the spectroscopy as we discussed

**Comment by nkanazawa1989** [comment]
pulled master and readd all the changes to solve the conflict.

**Comment by dcmckayibm** [comment]
Yes, please remove the spectroscopy to the community folder

**Comment by dcmckayibm** [comment]
Looks good, can we merge @nonhermitian

**Pull request merged**
