### PR TITLE
Docs/getting data from backend

### PR DESCRIPTION
**Pull request by lcapelluto**
### Summary

#869 Getting data from backend

### CODE REVIEW

**Comment by nonhermitian** [comment]
Still needs TOC.  This link goes no where: https://render.githubusercontent.com/view/adding_measurements.ipynb

**Comment by lcapelluto** [comment]
@nonhermitian Why would that link go somewhere?

**Comment by nonhermitian** [comment]
I don’t know. It is in your tutorial.

**Comment by lcapelluto** [comment]
@nonhermitian Indeed, I see it now. Thanks for catching my mistake!

**Pull request merged**
