### PR TITLE
Discriminator tutorial

### PR DESCRIPTION
**Pull request by eggerdj**
### Summary
Moving discriminator tutorial from qiskit-ignis to qiskit-iqx-tutorials

### Details and comments
The ignis discriminator tutorial was previously in qiskit-ignis. However, it should live in qiskit-iqx-tutorials.

### CODE REVIEW

**Comment by nonhermitian** [comment]
Missing copyright and version table, but good otherwise.

**Comment by eggerdj** [comment]
@nonhermitian Added copyright and version table. Updated code to remove deprecation warning, ran NB from top to bottom.

**Comment by nonhermitian** [comment]
Why not use `plot_histogram` instead of bar plot for the final figure?

**Comment by eggerdj** [comment]
@nonhermitian Good point, I updated the plotting.

**Pull request merged**
